name: Actualizar Extremos ClimaMeteoInfo

on:
  schedule:
    # Se ejecuta de forma automática cada 15 minutos de forma invisible
    - cron: '*/15 * * * *'
  workflow_dispatch: # Te permite pulsar un botón en GitHub para probarlo al instante

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Consultar Endpoint de Extremos
      run: |
        curl -s "https://climameteoinfo.com" -o datos-estacion.json

    - name: Guardar datos en el repositorio
      run: |
        git config --global user.name "MeteoTetuan Bot"
        git config --global user.email "meteotetuan@gmail.com"
        git add datos-estacion.json
        git commit -m "Automatización: Extremos climatológicos actualizados [skip ci]" || exit 0
        git push
